### PR TITLE
Update consensus.md

### PR DESCRIPTION
**Pull request by AdamZWinter**

### CODE REVIEW

**Comment by tzarebczan** [comment]
Thanks for this PR @AdamZWinter . @lyoshenka / @kauffj will be beefing up some of the docs on lbry.tech this week, so I'll let them review to see if anything else needs to be added here (though it does look like it talks about both the targeting + difficulty).

**Comment by lyoshenka** [comment]
That whole article should just be replaced with a link to https://spec.lbry.io/#consensus

**Comment by AdamZWinter** [comment]
@lyoshenka I found that page very helpful with the way it presented the structure of the hash algorithm.  This is the first/only page I've found that explained this at this level.  I like that it's somewhere between vaguely saying its a combination of some hash functions and having to decipher the source code.    That said, I've edited the other part to just link directly to the white paper, like you've suggested.

**Comment by lyoshenka** [comment]
:+1:

**Pull request merged**
