### PR TITLE
added 'Android build in 10 steps' resource

### PR DESCRIPTION
**Pull request by akinwale**

### CODE REVIEW

**Comment by kauffj** [comment]
1. I think this should just live in lbry-android and presumably replace `BUILD.md` since it is specific to our app. If we had a resource article on how to build on Android _generally_, that would make sense to go on lbry.tech
1. Are these the instructions one should be using currently? I actually was trying to go through the old BUILD.md just today, but only had an hour and did not finish.

**Comment by akinwale** [comment]
@kauffj
1. The reason for this is to serve as a quick start to being able to build the app. The `BUILD.md` is meant to be a more detailed document which explains the steps. 
2. These are the current instructions. I plan to update `BUILD.md` with the commands in this one.

Additionally, I plan to separate the React Native app code into a separate repository, so that it will be imported as a submodule, so this will eventually end up being a build guide for the sdk on Android.

**Comment by kauffj** [comment]
@akinwale I modified substantially, please review again before merging

**Comment by kauffj** [comment]
@akinwale mergable?

**Comment by akinwale** [comment]
Yes. Will merge.

**Pull request merged**
