### PR TITLE
New navigation! And, fixes

### LINKED ISSUE #236: Finish Navigation

### LINKED ISSUE #250: Dynamically calculate scrollbar on /spec
Currently, lbry.tech/spec is showing a double scrollbar: one for the iframe, and one for the site itself.

### PR DESCRIPTION
**Pull request by NetOperatorWibby**
Closes #236
Closes #250 

I added links I felt should be added to the navigation drawer, but y'all should review for yourselves.

Responsive styling for the new navigation should be added to this PR.

### CODE REVIEW

**Comment by NetOperatorWibby** [comment]
@lyoshenka Jeremy is having the same issue and is also on Linux. I wonder if the Sass module I'm using doesn't have bindings for Linux. What's the error message you get?

**Comment by kauffj** [comment]
AHA! It is not just me. @NetOperatorWibby neither `npm run css` nor `npm run watch` issue any relevant errors or warnings. `npm i` does output the following warnings, but none seem relevant:

```
npm WARN optional Skipping failed optional dependency //win-node-env:
npm WARN notsup Not compatible with your operating system or architecture: win-node-env@0.4.0
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
npm WARN enoent ENOENT: no such file or directory, open '/home/kauffj/code/lbry.tech/app/components/api/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kauffj/code/lbry.tech/app/components/client/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kauffj/code/lbry.tech/app/components/ecosystem/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kauffj/code/lbry.tech/.git/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kauffj/code/lbry.tech/.idea/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kauffj/code/lbry.tech/app/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kauffj/code/lbry.tech/documents/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kauffj/code/lbry.tech/node_modules/package.json'
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none was installed.
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none was installed.
```

**Comment by NetOperatorWibby** [comment]
I wonder why there are so many searches for `package.json`. I though [`link-module-alias`](https://github.com/Rush/link-module-alias) could possibly be the issue due to symlinking but I didn't see Linux/Ubuntu issues in the repo.

**Comment by NetOperatorWibby** [comment]
Jessop and I had a call and he showed me this branch working on Arch Linux.

**Comment by jessopb** [comment]
The docs don't mention that you have to cp .env.sample to .env before it will run.... I don't know if that's it.
Installed fresh webdaemon and lbry.tech. git pulled paul's navigation branch. 
lbrytechdropdowns

**Comment by NetOperatorWibby** [comment]
@kauffj I tried doing this with CSS and was unsuccessful. JS is the way to go but I don't think I'm going to have a working solution anytime soon.

**Comment by kauffj** [comment]
I'm happier keeping the navigation as-is than introducing it with the pathing issues. 

I don't think it's that important to change it anyway.

**Pull request closed without merging**
