### PR TITLE
Updated README to its desired location

### PR DESCRIPTION
**Pull request by sanketsingh24**
I don't know how to change it on [the website](https://lbry.tech/contribute#coding), just couldn't find the file. If someone tells me where it is located, I will change and push. :)

### CODE REVIEW

**Comment by tzarebczan** [comment]
hey @sanketsingh24, thanks for the contribution. This is meant to be a hyperlink to our Glossary for the term `Readme`, not a specific readme. Want to add readme to https://github.com/lbryio/lbry.tech/blob/master/documents/glossary.md with a definition from and link back to https://lbry.tech/resources/repository-standards ?

**Comment by sanketsingh24** [comment]
I think you did not get me, as I could've explained better. 

If you open [Coding section in Contributor's Guide](https://lbry.tech/contribute#coding) and move to Point No.3 "Get set up"

deepinscreenshot_select-area_20181009164932

Here, README is a hyperlink which links to https://lbry.tech/glossary#README. If it would have been https://lbry.tech/glossary#readme, It would be working. 

I could not find the Contributor's guide to change that, so can you please tell me where it is located?

**Comment by tzarebczan** [comment]
@sanketsingh24 ah, now I understand better, thanks.  I've opened up https://github.com/lbryio/lbry.tech/issues/176 to address this.

Can we send you some [LBC in appreciation](https://lbry.io/faq/appreciation) for pointing this out?

**Comment by sanketsingh24** [comment]
Thanks for the appreciation, and sorry for not explaining it better on the first try :)

**Pull request closed without merging**
